# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: directededge 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "directededge"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Directed Edge"]
  s.date = "2016-09-16"
  s.description = "Bindings for the Directed Edge webservices API"
  s.email = "info@directededge.com"
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    ".gitignore",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "directededge.gemspec",
    "examples/example_store.rb",
    "lib/directed_edge/container_proxy.rb",
    "lib/directed_edge/database.rb",
    "lib/directed_edge/history.rb",
    "lib/directed_edge/history_entry.rb",
    "lib/directed_edge/item.rb",
    "lib/directed_edge/item_query.rb",
    "lib/directed_edge/link.rb",
    "lib/directed_edge/resource.rb",
    "lib/directed_edge/update_job.rb",
    "lib/directed_edge/xml.rb",
    "lib/directededge.rb",
    "test/helper.rb",
    "test/test_directededge.rb"
  ]
  s.homepage = "http://developer.directededge.com/"
  s.rubygems_version = "2.4.8"
  s.summary = "Bindings for the Directed Edge webservices API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
      s.add_runtime_dependency(%q<oga>, [">= 0"])
    else
      s.add_dependency(%q<rest-client>, [">= 0"])
      s.add_dependency(%q<oga>, [">= 0"])
    end
  else
    s.add_dependency(%q<rest-client>, [">= 0"])
    s.add_dependency(%q<oga>, [">= 0"])
  end
end

