# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: directed-edge 0.3.3 ruby lib

Gem::Specification.new do |s|
  s.name = "directed-edge"
  s.version = "0.3.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Directed Edge"]
  s.date = "2016-10-05"
  s.description = "Bindings for the Directed Edge webservices API"
  s.email = "info@directededge.com"
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    ".gitignore",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "directed-edge.gemspec",
    "examples/example_store.rb",
    "lib/directed_edge.rb",
    "test/helper.rb",
    "test/test_directed_edge.rb"
  ]
  s.homepage = "http://developer.directededge.com/"
  s.rubygems_version = "2.5.1"
  s.summary = "Bindings for the Directed Edge webservices API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
    else
      s.add_dependency(%q<rest-client>, [">= 0"])
    end
  else
    s.add_dependency(%q<rest-client>, [">= 0"])
  end
end

