source 'http://rubygems.org'

gem 'rest-client'
gem 'libxml-ruby'

group :development do
  gem "rake", "0.8.7"
  gem 'rdoc', '~> 3.12'
  gem 'bundler', '~> 1.0.0'
  gem 'jeweler', '~> 1.8.3'
  gem 'rcov', '>= 0'
end
