#!/usr/bin/ruby

tests = {}
tests['Ruby'] = 'rake test'
tests['Python'] = 'python directed_edge_test.py'
tests['PHP'] = 'phpunit DirectedEdgeTest.php'
tests['Java'] = 'ant test'

tests.each do |language, command|
  Dir.chdir(language)
  puts '================================================================================'
  puts "#{language} Tests"
  puts '================================================================================'
  system(command) or raise "#{language} tests failed."
  Dir.chdir('..')
end
